"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getGameData = exports.getGameStatus = exports.getPlayerData = exports.tokenify = void 0;
var tokenify_1 = require("./tokenify");
Object.defineProperty(exports, "tokenify", { enumerable: true, get: function () { return tokenify_1.tokenify; } });
var getPlayerData_1 = require("./getPlayerData");
Object.defineProperty(exports, "getPlayerData", { enumerable: true, get: function () { return getPlayerData_1.getPlayerData; } });
var getGameStatus_1 = require("./getGameStatus");
Object.defineProperty(exports, "getGameStatus", { enumerable: true, get: function () { return getGameStatus_1.getGameStatus; } });
var getGameData_1 = require("./getGameData");
Object.defineProperty(exports, "getGameData", { enumerable: true, get: function () { return getGameData_1.getGameData; } });
