"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getPlayerFriendRequests = exports.getPlayerUserID = exports.updatePlayerData = exports.getGameData = exports.getGameStatus = exports.getPlayerData = exports.tokenify = void 0;
var tokenify_1 = require("./tokenify");
Object.defineProperty(exports, "tokenify", { enumerable: true, get: function () { return tokenify_1.tokenify; } });
var getPlayerData_1 = require("./getPlayerData");
Object.defineProperty(exports, "getPlayerData", { enumerable: true, get: function () { return getPlayerData_1.getPlayerData; } });
var getGameStatus_1 = require("./getGameStatus");
Object.defineProperty(exports, "getGameStatus", { enumerable: true, get: function () { return getGameStatus_1.getGameStatus; } });
var getGameData_1 = require("./getGameData");
Object.defineProperty(exports, "getGameData", { enumerable: true, get: function () { return getGameData_1.getGameData; } });
var updatePlayerData_1 = require("./updatePlayerData");
Object.defineProperty(exports, "updatePlayerData", { enumerable: true, get: function () { return updatePlayerData_1.updatePlayerData; } });
var getPlayerUserID_1 = require("./getPlayerUserID");
Object.defineProperty(exports, "getPlayerUserID", { enumerable: true, get: function () { return getPlayerUserID_1.getPlayerUserID; } });
var getPlayerFriendRequests_1 = require("./getPlayerFriendRequests");
Object.defineProperty(exports, "getPlayerFriendRequests", { enumerable: true, get: function () { return getPlayerFriendRequests_1.getPlayerFriendRequests; } });
